DEFAULT_FLAG    = 0x00
FIN_FLAG        = 0x01
SYN_FLAG        = 0x02
PSH_FLAG        = 0x04
ACK_FLAG        = 0x08

PAYLOAD_SIZE    = 64
WINDOW_SIZE     = 4
TIMEOUT_TIME    = 1
TIMEOUT_LISTEN  = 30
MAX_BUFFER      = 10
MESSAGES_LIMIT  = 20

HEARTBEAT_INTERVAL = 1

MAX_WIDTH       = 40